# Generated by Django 4.2.5 on 2023-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
